# Generated by Django 6.0.6 on 2026-06-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_scholarship', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('criteria', models.TextField()),
                ('documents_required', models.TextField()),
            ],
        ),
    ]
