# Generated by Django 4.0.10 on 2026-06-28 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholar', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webuserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
